---
- name: Installing Apache, setting timezone, displaying custom HTML page, installing PHP, and disabling default Apache >  hosts: all
  become: yes
  tasks:
    - name: update apt cache
      apt:
        update_cache: yes
    - name: Installing Apache
      package:
        name: apache2
        state: present

    - name: Setting timezone to Africa/Lagos
      command: timedatectl set-timezone Africa/Lagos
      register: set_timezone_result
      ignore_errors: yes

    - name: printting hostname on server
      tags: printf
      shell: echo "<h1>HEYO MY HOSTNAME IS $(hostname -f)</h1>" > /var/www/html/index.html

    - name: Ensuring Apache is running
      service:
        name: apache2
        state: started
        enabled: true
      notify:
        - restart apache

  handlers:
    - name: restarting apache
      service:
        name: apache2
        state: restarted
